### ISSUE TITLE
Expose card type management in editor

### ISSUE THREAD

**Issue by nsrosenqvist** [HolonProduction/godot_kanban_tasks#1]
Love this addon! Great work! On the screenshots you display different card types, e.g. Task and Bug. I can't find how to add this anywhere inside the editor, is this functionality not yet exposed or am I just missing something obvious?

**Comment by HolonProduction** [comment]
The functionality is not yet exposed to the editor. I plan to add a settings panel to manage the categories but I don't have much time to work on the project right now. In the meantime you can edit the json file, in which the tasks are stored. It should be located under `res://addons/kanban_tasks/data.json` once you activated the plugin once.
The key `categories` stores an array of category objects. Have a look at [this example](https://github.com/HolonProduction/godot_kanban_tasks/blob/d417e1fb7a68efaa119bcb4c4fb36a79253e7e30/examples/data1.json) to see what it contains.
__Note:__ There has to be at least one category otherwise the addon will crash.

You can also customize the stages in this file. I hope the way it is set up is understandable from the example.

**Comment by nsrosenqvist** [comment]
@HolonProduction thanks! I'll do that for now!

**Comment by HolonProduction** [comment]
There is now a settings button where you can configure the categories. I don't know much about updating plugins via the asset lib so be sure to make a backup of your `data.json` before updating in an existing plugin.

**Comment by nsrosenqvist** [comment]
Amazing! Thank you so much!
