### ISSUE TITLE
Plugin wont work

### ISSUE THREAD

**Issue by Cablefish1** [HolonProduction/godot_kanban_tasks#12]
I'm fairly certain i'm doing something wrong since this is the first plugin i've tried to install but here you are anyways in case other noobs try the same thing and something can be improved on your end.

I'm getting this crash when i try to activate the plugin.

```
Unable to load addon script from path: 'res://addons/kanban_tasks/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/kanban_tasks/plugin.cfg' to prevent further errors.
```
Steps to reproduce:

1:
Download zip from github repository main page:
https://github.com/HolonProduction/godot_kanban_tasks

2:
Extract addons into project folder

3: 
Open Godot Steam (3.5.1.) and open the project

4:
Go to project settings --> Plugins and try to check Enable box.

Godot says i'm using 2.0alpha of the plugin.

**Comment by HolonProduction** [comment]
When you download the zip from Github you will recieve the contents of the `master` branch which was already ported to Godot 4 (and is currently unstable). Since you are using Godot 3 you should download the contents of 3.x branch (the plugin version should be 1.1).
The best option to install plugins is the godot asset lib, which is also available through the editor. [Here](https://docs.godotengine.org/en/stable/community/asset_library/using_assetlib.html#in-the-editor) you can find a quick introduction. This plugin is available from there as well: https://godotengine.org/asset-library/asset/1245.

**Comment by Cablefish1** [comment]
Thanks a bunch and sorry for taking your time.
