### ISSUE TITLE
Enhancement Request: Group or Link Tasks

### ISSUE THREAD

**Issue by kminardo** [HolonProduction/godot_kanban_tasks#5]
First off, fantastic work on this plugin! I'm really enjoying how convenient it is having tasks right inside the editor and project. The look, feel and functionality is absolutely on point.

An idea for a enhancement:
I'll often find myself needing multiple cards to complete larger features and it all gets a bit disconnected as I work through the tasks. It may be useful to add some kind of task grouping or linking so that users can break up their workflow into smaller chunks without losing context of what those tasks are building towards.

Current workaround I'm using is listing sub-tasks inside the description, which is okay, but it seems like there could be a better solution that increases sub-task visibility.

**Comment by HolonProduction** [comment]
I want to add more details to a task in future. So instead of just having a description it would in addition feature a checklist of steps which one need to complete for the task. I think this would help with such subtasks.

But before I can work on those checklists, I need to refactore large parts of the code base. Because each new feature will make refactoring harder in future. I plan to start with refactoring once GDScript 2.0 seems stable to me (hopefully soon).

**Comment by HolonProduction** [comment]
The step list feature is now implemented.
